---

- name: Aanmaken lvs
  lvol: vg={{ item.vg }} lv={{ item.lv }} size={{ item.size }}
  with_items: "{{fsinfo}}" 
  when: item.vg is defined

- name: Aanmaken filesystemen
  filesystem: dev=/dev/{{ item.vg }}/{{ item.lv }} fstype=ext4
  with_items: "{{fsinfo}}"
  when: item.vg is defined and item.fs is defined
 
- name: Maken mounts
  mount: name={{ item.fs }} src=/dev/{{ item.vg }}/{{ item.lv }} fstype=ext4 state=mounted opts=defaults,acl,nofail
  with_items: "{{fsinfo}}"
  when: item.vg is defined and item.fs is defined

- name: zetten rechten mountpoints
  file: path={{ item.fs }} state=directory mode={{ item.mode }} owner={{ item.user }}  group={{ item.group }}
  with_items: "{{fsinfo}}" 
  when: item.user is defined
